# Generated by Django 3.2.8 on 2021-11-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211116_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='last_name',
        ),
    ]
