# Generated by Django 3.2.8 on 2021-11-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211117_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='details',
            name='las_name',
        ),
    ]
