# Generated by Django 3.2.8 on 2021-11-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211117_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
