# Generated by Django 3.2.8 on 2021-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vt_help', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsStory',
            new_name='placesOfInterest',
        ),
    ]
