# Generated by Django 3.2.8 on 2021-11-04 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vt_help', '0002_rename_newsstory_placesofinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesofinterest',
            name='author',
            field=models.CharField(default='rick', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placesofinterest',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
